-- TORNEO STUDIO LITE: BASE DE DATOS DE VOTACIÓN
-- Ejecuta TODO este archivo en Supabase → SQL Editor.

create table if not exists public.nominees (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  nominee_id bigint not null references public.nominees(id) on delete cascade,
  voter_id text not null,
  created_at timestamptz not null default now(),
  constraint votes_one_vote_per_voter unique (voter_id)
);

insert into public.nominees (name) values
('Creador 1'), ('Creador 2'), ('Creador 3'), ('Creador 4'), ('Creador 5'),
('Creador 6'), ('Creador 7'), ('Creador 8'), ('Creador 9'), ('Creador 10')
on conflict (name) do nothing;

create or replace view public.nominee_counts as
select
  n.id as nominee_id,
  n.name,
  count(v.id)::bigint as votes
from public.nominees n
left join public.votes v on v.nominee_id = n.id
group by n.id, n.name;

-- Permite que la página pública lea la clasificación.
grant select on public.nominee_counts to anon, authenticated;

-- La página NO inserta directamente en votes.
-- Usa esta función para registrar un voto.
create or replace function public.cast_vote(p_nominee_id bigint, p_voter_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.nominees where id = p_nominee_id) then
    raise exception 'Nominado no válido';
  end if;

  insert into public.votes(nominee_id, voter_id)
  values (p_nominee_id, p_voter_id);

  return jsonb_build_object('already_voted', false);
exception
  when unique_violation then
    return jsonb_build_object('already_voted', true);
end;
$$;

grant execute on function public.cast_vote(bigint, text) to anon, authenticated;

-- Seguridad: evita que el navegador lea o escriba directamente la tabla de votos.
alter table public.votes enable row level security;
alter table public.nominees enable row level security;

drop policy if exists "no direct vote reads" on public.votes;
drop policy if exists "no direct vote inserts" on public.votes;

-- El conteo público se obtiene mediante la vista.
-- Los votos individuales quedan protegidos por RLS.
